# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_test_time1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='time1',
            new_name='timestr',
        ),
    ]
