# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20180725_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='timestr',
            new_name='when',
        ),
    ]
