# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_auto_20180725_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('data', models.TextField()),
            ],
        ),
    ]
