# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0011_auto_20180730_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
